L = [1, "2", 3.0, [4]]
print("Original list:", L)
L.append("5 (new item)")
print("Appended list:", L)
print("Count of 1 in list:", L.count(1))
C = L.copy()
print("Copied list:", C)
L.extend(C)
print("Extended list:", L)
print("Index of 1:", L.index(1))
L.insert(2, "new item at index 2")
print("Inserted item:", L)
L.pop()
print("Popped last item:", L)
L.remove("2")
print("Removed '2':", L)
L.sort(key=str)
print("Sorted list:", L)
L.reverse()
print("Reversed list:", L)
L.clear()
print("Cleared list:", L)


